### ISSUE TITLE
Can you `@group_by` all columns but x,y,z?

### ISSUE THREAD

**Issue by pat-alt** [TidierOrg/TidierData.jl#39]
More of a question than an issue, but is there a way to `@group_by` all columns but columns `x`,`y`,`z`? The equivalent in `DataFrames` would be something like `DataFrames.groupby(df, DataFrames.Not([:x, :y, :z])`.

**Comment by kdpsingh** [comment]
Not yet but I think this is at least partially related to https://github.com/TidierOrg/TidierData.jl/issues/1. This is fixable.

**Comment by kdpsingh** [comment]
The eventual syntax for this will be `@group_by(-x, -y, -z)`.

**Comment by kdpsingh** [comment]
Sorry it took so long!

This works now as of #104, with the following syntax: `@group_by(df, -(x, y, z))` or `@group_by(df, !(x, y, z))`

Note that this syntax *doesn't* work: `@group_by(df, -x, -y, -z)`. While it is supportable, it is trickier to implement because it translates to `Cols(Not(:x), Not(:y), Not(:z))`, which is very different than `Not([:x, :y, :z])`. I'm not planning to implement it for now but may revisit in the future.

**Comment by pat-alt** [comment]
Awesome, thanks for this!
