### ISSUE TITLE
Various items for @summarize

### ISSUE THREAD

**Issue by ymer** [TidierOrg/TidierData.jl#47]
1.
`summarize` with `across` changes the names of the columns

As described in the docs: https://tidierorg.github.io/TidierData.jl/latest/examples/generated/UserGuide/across/

Tidyverse does not change the name of the columns. And I think this is the right approach. It is not a mutation, it is a summary, so it is still a value that pertains to the column name as it is, usually.

Also it is a hassle to rename the columns back.

2.
Tidyverse has a function `everything()` to select all columns when using `across`. This is often useful. `names(df)` can be used, but sometimes the column names will have changed in the chain.

3.
`group_by` with more than one item, followed by `summarize` returns a grouped dataframe with one less grouping.

```
dff = DataFrame(a = [1,2,2], b = [3,3,4], c=[3, 4, 5])
dfff = @chain dff begin
    @group_by(a, b)
    @summarize(m = mean(c))
end
```
`GroupedDataFrame with 2 groups based on key: a`

I think this is unfortunate. 
- It's unexpected for many users
- It's defined in an unusual way, based on the order of the items in `group_by`.
- It's non-transparent later in the code

Hadley Wickham agrees that it is not good:

> That’s because summarise() always peels off the last group, based on the logic that this group now occupies a single row so there’s no point grouping by it. This behaviour made perfect sense to me at the time I implemented it, but it’s been a long standing source of confusion among dplyr users (and it doesn’t make sense if your summary [returns multiple rows](https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-summarise/)).
> 
> Unfortunately, it would be very difficult to change this default now because a lot of code probably relies on it. Instead, we’re doing the next best thing: exposing the default behaviour more explicitly and making it easier to change. In dplyr 1.0.0, the code above will display a message telling you how the result has been grouped

However, TidierData doesn't have the issue of breaking a lot of existing code, so you could simply fix this mistake!

I recognize the argument that you are interested in making a clone of Tidyverse. But I think it is worth considering whether that includes cloning legacy mistakes.

**Comment by kdpsingh** [comment]
Thanks for engaging with the package and filing this issue! Here are some quick thoughts about each of them:

1. It's true that when using `across()`, tidyverse doesn't rename the column when you're using a single summary function. However, I believe that when you summarize across multiple functions, it *does* rename your columns. I think we can mimic this behavior in TidierData.jl, and an eventual goal will be to give users more control over the naming scheme like tidyverse does with the `.names` argument, but that's further off.

- [ ] Fix `across()` to not rename functions when using only one summary function.

2. `everything()` should be really easy to implement and is something I've been planning to do since it makes re-ordering columns much easier.

- [ ] Add support for `everything()`

3. This is a difficult one to deal with. While I've seen Hadley Wickham's point that this may have been a design mistake, tidyverse has also gone back and forth on the key related issue you shared, which is whether `summarize()` can allow for returning more than one row per group. This used to be not allowed, then was allowed, and now again is not allowed (with `enframe()` being used for multi-row summaries). Without getting too philosophical, the main thing that users gain from using Tidier.jl in my mind is a conscious decision to let people bring their tidyverse mental model over to Julia. For that reason, I'm very hesitant to change an underlying behavior in Tidier.jl to diverge from tidyverse unless that behavior changes in tidyverse itself. Even though Julia doesn't have the baggage from legacy code, I do think people's mental model is a form of legacy code. I do think we should add support for in-line grouping using `by` which will always ungroup. If tidyverse changes course, I'm happy to update the behavior accordingly.

I am planning to add tidylog-like support to Tidier.jl, which will help users understand how the grouping behaves along with other info needed for troubleshooting. Am open to discussion.

**Comment by kdpsingh** [comment]
Thinking more on your 3rd point, I'd like to get some feedback on how people would like Tidier.jl's `@summarize' to behave, especially given the desire from the R tidyverse team to change the behavior, with their main hesitation being due to this being a breaking change.

How would you like `@summarize` to behave?

Mark this comment with a thumbs up if you think we should keep existing tidyverse behavior (peel off one layer of grouping)

Give a thumbs down if you feel that it should remove all grouping, thus diverging from R tidyverse.

We may or may not act on the results of this vote but I want to get a sense of how ppl feel.

**Comment by rdboyes** [comment]
My feeling is that the default behaviour of code written in Tidier should be, if possible, identical to tidyverse behaviour. Adding options for alternate “better” behaviour is reasonable, but isn’t the whole point to have it work the same way?

**Comment by kdpsingh** [comment]
I think @rdboyes is right. Outside of GitHub (https://x.com/kdpsinghlab/status/1701939842253255069?s=46&t=PEX2NKcgCDoTOe3kHQFmDA), we had at least one additional person ask us to keep tidyverse behavior and one person who suggested that `@summarize` should *not* ungroup at all. What that tells me is that people may have multiple different views on what should be the default behavior -- rather than impose a set of personal preferences, we should stick to matching tidyverse behavior.

I think our guiding principle is that "if it's different from tidyverse, it's a bug" unless there's something materially different about Julia (eg data types) that we want to capture on how functions/macros are named.

We will keep the existing behavior. I do plan to add tidylog and `by =` functionality that will help users see what Tidier.jl is doing at each step and allow for in-line grouping.

**Comment by kdpsingh** [comment]
Looping back on this issue.

The main outstanding item from this item is that we wanted to make it possible for `across()` to *not* rename columns when only a single summary function is provided. When you use `across()` instead of `@mutate()`, this is wrapping `transform()` in DataFrames.jl.

The challenge here is that `transform()` provides a keyword argument `renamecols = true` which applies to *every* `across()` function used within it. Thus, if you use multiple `across()` functions inside of `@mutate()`, then we would need to check every one of them to ensure that *none* of them exceed 1 summary function before setting `renamecols = false`. If any individual `across()` function includes more than 1 summary function, then the name conflict would raise an error.

Trying to fix this could introduce unexpected and inconsistent behavior as compared to tidyverse, so my inclination is to leave the current behavior in place, which is predictable: every use of across creates a new column named with a `column_function` scheme.
