### ISSUE TITLE
How can I edit the name of all columns?

### ISSUE THREAD

**Issue by ymer** [TidierOrg/TidierData.jl#54]
In Tidyverse I could do this to remove all "/" symbols in column names:

`rename_with(~ str_replace_all(., "/", ""))`

Is there a way to do this in a Tidier chain?

**Comment by kdpsingh** [comment]
`rename_with` isn't implemented yet. There *is* a way to do this within a chain using existing Julia syntax. Will share in a bit, but either way will leave this issue open until we implement `rename_with`.

**Comment by drizk1** [comment]
below is a very preliminary `rename_with` macro that can be used with `str_replace_all` in a Tidier Chain to accomplish your goal.

```
using DataFrames: rename

df = DataFrame("A/B" => [1, 2])
macro rename_with(df, func)
    return quote
        cols = names($(esc(df)))
        new_cols = map(c -> $(esc(func))(string(c)), cols)
        rename_map = Dict(zip(cols, new_cols))
        rename($(esc(df)), rename_map)
    end
end 

@chain df begin
    @rename_with( str -> str_replace_all(str, "/", ""))
end

@rename_with(df, str -> str_replace_all(str, "/", ""))
```

Of note, plz use the most recent TidierStrings version (not yet released because there are a few other changes I am planning before releasing still, so u will have to first update via `] add TidierStrings#main` )

**Comment by kdpsingh** [comment]
`@rename_with()` has been added to v0.13.0 and is now merged.
