### ISSUE TITLE
Lookup table of vectorized functions

### ISSUE THREAD

**Issue by jfb-h** [TidierOrg/TidierData.jl#6]
It would be nice to list all of the functions that are vectorized/broadcasted by default in the [docs](https://tidierorg.github.io/Tidier.jl/dev/examples/generated/UserGuide/autovec/) or maybe have a link to where they are specified in the repo. I was unsure about the behavior of `first`, for example.

**Comment by kdpsingh** [comment]
A package-level global variable `not_vectorized[]` has now been exposed in 66b8639eabc94f6519a4f0f27af2fe3dd546729b.

This will allow other users and other packages to modify the do-not-vectorized "list" (technically a vector of symbols).

Leaving this issue open until we add documentation for it. Also planning to take advantage of this feature within the TidierCats.jl package.

**Comment by kdpsingh** [comment]
Note: we removed it as a package-level global mainly because I couldn't get it to work as expected. However, I later discovered the reason I couldn't get it to work was that my CI dependencies were caching package installations so weren't updating a package to take advantage of this code.

I'm likely going to leave it as a package-internal variable but will still plan to add documentation for how other packages can access it and modify it.

**Comment by kdpsingh** [comment]
This is now documented at https://tidierorg.github.io/TidierData.jl/latest/examples/generated/UserGuide/autovec/
