### ISSUE TITLE
"cumsum" function in mutate

### ISSUE THREAD

**Issue by jfish-fishj** [TidierOrg/TidierData.jl#89]
When I try to create a new variable that is the cumulative sum of another variable I get incorrect results:

`using DataFrames
using Tidier

df = DataFrame(a = 1:10)
df = @chain df begin
    @mutate(
        cum_a_tidier = cumsum(a)
        )
end

df[!, :cumulative_a_base] = cumsum(df[!, :a])
 `

This results in the tidier version returning an array containing only the value for "a" for that row, whereas the base version returns the correct result.

**Comment by kdpsingh** [comment]
Just to close the loop on this, this issue was fixed many versions ago. However, there is a really old version of Tidier.jl that prevented upgrades to TidierData.jl. I would suggest removing Tidier.jl and TidierData.jl and reinstalling Tidier.jl, and that should fix the issue. All of the recent versions of Tidier.jl are future-proofed.

Here's what I see in the current version of TidierData.

```julia
using Tidier

julia> df = DataFrame(a = 1:10)
10×1 DataFrame
 Row │ a     
     │ Int64 
─────┼───────
   1 │     1
   2 │     2
   3 │     3
   4 │     4
   5 │     5
   6 │     6
   7 │     7
   8 │     8
   9 │     9
  10 │    10

julia> @chain df begin
           @mutate(cum_a_tidier = cumsum(a))
       end
10×2 DataFrame
 Row │ a      cum_a_tidier 
     │ Int64  Int64        
─────┼─────────────────────
   1 │     1             1
   2 │     2             3
   3 │     3             6
   4 │     4            10
   5 │     5            15
   6 │     6            21
   7 │     7            28
   8 │     8            36
   9 │     9            45
  10 │    10            55
```

**Comment by jfish-fishj** [comment]
yeah, the issue with the old version preventing me from upgrading seems to be my problem; I had upgraded the package but didn't check to see that it was successful. thanks for the quick response!
